### ISSUE TITLE
WebRTC playback not working

### ISSUE THREAD

**Issue by hernanrz** [AirenSoft/OvenMediaEngine#1057]
**Describe the bug**
WebRTC never starts playing after upgrading OME, LLHLS playback works ok

**To Reproduce**
1. Use ome docker image with 0.15.1 0.15.0 or 0.14.18 tags with Server.xml: https://gist.github.com/hernanrz/c30f0c319e4321c3830edf79ad63bf2c
2. Start stream with obs
3. Attempt webrtc playback on demo page (from a remote machine, when testing on the same machine the server is running it works)
4. Player is stuck loading then shows the play button again

**Expected behavior**
Playback should start

**Logs**
[ome.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10892464/ome.txt)

**Server (please complete the following information):**
 - OS: Docker
 - OvenMediaEngine Version: 0.15.1

**Player (please complete the following information):**
 - Device: Desktop
 - OS: Windows 11
 - Browser Firefox
 - Version Latest

**Additional context**

**Comment by getroot** [comment]
what was your docker command?
Also what was the playback url for your webrtc?


> from a remote machine, when testing on the same machine the server is running it works

Does it mean that if you try to play it on a machine running OME, it will play fine? If so, have you checked your firewall? Are 10000-10005/udp and 3478/tcp open to the outside?

**Comment by hernanrz** [comment]
we're using docker-compose up

with docker-compose.yml


```
version: '3.3'
services:
  ovenmediaengine:
      image: ovenmediaengine
      env_file: .env
      network_mode: host
      volumes:
          - $SSL_FULLCHAIN_PATH:/opt/ovenmediaengine/fullchain.pem:ro
          - $SSL_PRIVKEY_PATH:/opt/ovenmediaengine/privkey.pem:ro
          - $SSL_CERT_PATH:/opt/ovenmediaengine/cert.pem:ro
          - $RECORDINGS_PATH:/mnt/recordings
          - $DVR_PATH:/tmp/ome_dvr
      restart: always
      labels:
        autoheal: true
      deploy:
        resources:
          limits:
            memory: 50G
```

Dockerfile
```
FROM airensoft/ovenmediaengine
RUN apt-get update && apt-get install -y curl


WORKDIR /opt/ovenmediaengine/bin

COPY ./Server.xml /opt/ovenmediaengine/bin/origin_conf/Server.xml
COPY ./Logger.xml /opt/ovenmediaengine/bin/origin_conf/Logger.xml
COPY EdgeConfig.xml ./edge_conf/Server.xml

COPY entrypoint.sh .

CMD ["bash", "entrypoint.sh"]
```

> Does it mean that if you try local playback on a machine running OME, playback works fine? If so, have you checked your firewall? Are 10000-10005/udp and 3478/tcp open to the outside?

Correct, I will check the firewall on the server
