### ISSUE TITLE
Request to test hardware transcoding

### ISSUE THREAD

**Issue by getroot** [AirenSoft/OvenMediaEngine#429]
OME now has hardware transcoding capabilities. You can try this feature in the latest master branch. Please refer to the manual below for details.

https://airensoft.gitbook.io/ovenmediaengine/v/master/transcoding/gpu-usage

We welcome all comments, such as bugs, improvements, and issues in the manual.

Your comments on this thread will help a lot in improving OvenMediaEngine.

Thank you for your contribution.

**Comment by fcqpl** [comment]
Hello,
Propably Oven not seeing my Quadro.

Docker-compose:
```
  ovenmediaengine:
    image: airensoft/ovenmediaengine:dev
    ports:
      - 443:443
      - 1935:1935
      - 3333:3333
      - 3334:3334
      - 3478:3478
      - 8080:8080
      - 9000:9000
      - 9999:9999/udp
      - 4000-4005:4000-4005/udp
      - 10006-10010:10006-10010/udp
    environment:
      - TZ=Europe/Warsaw
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    volumes:
      - ./oven_origin_conf:/opt/ovenmediaengine/bin/origin_conf
      - ./ssl:/etc/docker_ssl_cert
    restart: always
    runtime: nvidia
    networks:
      - streaming-net
```

Server.xml and log:
[logs.md](https://github.com/AirenSoft/OvenMediaEngine/files/6787719/logs.md)
[Server.xml.md](https://github.com/AirenSoft/OvenMediaEngine/files/6787720/Server.xml.md)

When I setup other container with nvidia-docker it's working correctly.
```
root@oven:/opt/streaming# nvidia-smi
Fri Jul  9 01:11:13 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 465.27       CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA Quadro K...  Off  | 00000000:06:10.0 Off |                  N/A |
| 42%   35C    P0     2W /  39W |    137MiB /  4043MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1059      G   /usr/lib/xorg/Xorg                  2MiB |
|    0   N/A  N/A   2397448      C   ffmpeg                            129MiB |
+-----------------------------------------------------------------------------+

```

Oven isn't supporting ABR in HLS/DASH/WebRTC?
