### ISSUE TITLE
hardware acceleration with Nvidia GPU through docker image not working according to the OME logs(incorrectly setup..?)

### ISSUE THREAD

**Issue by magnuszetterberg** [AirenSoft/OvenMediaEngine#740]
**PROBLEM**
When starting your docker image with this docker docker-compose.yml
and this Server.xml with hardware acceleration set to true, im still getting a warning that there is no supported hardware support for OME.

```
version: '3.3'
services:
    ovenmediaengine:
        ports:
            - '1935:1935'
            - '3478:3478'
            - '3333:3333'
            - '3334:3334'
            - '8080:8080'
            - '9000:9000'
            - '9999:9999/udp'
            - '8081:8081'
            - '8082:8082'
            - '4000-4005:4000-4005/udp'
            - '10006-10010:10006-10010/udp'
            # - '80:80'
            # - '443:443'
        volumes:
            - ./config/ome-origin-conf:/opt/ovenmediaengine/bin/origin_conf
            - ./config/ome-edge-conf:/opt/ovenmediaengine/bin/edge_conf
            - /etc/letsencrypt/archive/<lets encrypt path>:/opt/ovenmediaengine/bin/cert
        restart: unless-stopped
        image: 'airensoft/ovenmediaengine:dev'
        deploy:
          resources:
            reservations:
              memory: 64Gb
              devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
```
Origin_conf/Server.xml
[Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/8528725/Server.xml.txt)

Running the nvidia-smi command on the host/and inside the docker container I get these result

(from the physical computer)
```
Thu Apr 21 06:31:31 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-80GB      On   | 00000000:00:06.0 Off |                    0 |
| N/A   28C    P0    49W / 400W |      0MiB / 81252MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

(From inside the Docker container)

```
root@94141a9089d3:/opt/ovenmediaengine/bin# nvidia-smi
Thu Apr 21 06:42:16 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-80GB      On   | 00000000:00:06.0 Off |                    0 |
| N/A   29C    P0    49W / 400W |      0MiB / 81252MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

This suggests to me that:

1 - my host works with the nvidia cuda environment
2 - my container that is started through the docker-compose.yml file can reach the gpu on the host
3 - The Server.xml on the origin is setup according to the documentation.

**EXPECTATION**

I should not get a warning in the console log mentioning that there is "no supported hardware accelleration" and the GPU should be able to utilize the GPU for handling the streams coming into OME - and thus offloading the CPU.

**RESULT**
In the logs when running the "docker compose up" command, the log displayed in the console should not display a warning with:
`[2022-04-21 06:41:27.822] W [OvenMediaEngine:1] Transcoder | transcoder_application.cpp:46   | There is no supported hardware accelerator`

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information
0.13.2  (image: 'airensoft/ovenmediaengine:dev')

- Encoder information
Not applicable

- Player information
Not applicable yet

- URL
Not applicable yet
Please tell me which address you used to send and play. You can hide IP or Domain.

- Operating system and version
OME server

```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**SETUP INFORMATION AND LOGS**

Console log from when starting the container with "docker compose up"
[console.log](https://github.com/AirenSoft/OvenMediaEngine/files/8528756/console.log)

logfile from inside the docker container
[var-logs-ovemediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/8528758/var-logs-ovemediaengine.log)

**OTHER HELPFUL INFORMATION**
The server which runs the docker container seems to work just fine in general regarding cuda/nvidia...
The documents points to different scripts which should be run, but since i'm not using the source code in it self, only the configuration files for the server and then starting the docker - I then presume that the docker image contains all the necessary drivers/features etc which should make this work.

It might be that I´m misunderstanding some parts, but since in the instructions, from what I can tell, when you have the run the last command "sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi" and it spits out a working reply in the console that it can reach the nvidia-smi binary - the OME server with my Server.xml should be able to use the gpu on the server host..

Please help!  =)
