### ISSUE TITLE
Multiple synchronized videos in LLHLS

### ISSUE THREAD

**Issue by p4block** [AirenSoft/OvenMediaEngine#795]
**PROBLEM**
Right now, each of our streaming boxes delivers three simultaneous feeds to OME which are then played back with OMP. On WebRTC this works fine, and they stay synchronized. 

However on LLHLS, even though it works fine and the catchup mechanisms attempt and succeed to sync the videos, sometimes after a while or even on fresh starts one of the three videos will be consistently and significantly delayed from the other two (a full slice?).

Streamer -(1)-> OME -(2)-> Players

I suspect there's two problematic areas here, and with LLHLS (2) is where the problem's at. 

**EXPECTATION**
The three videos stay mostly synchronized, with some catchup action here and there to be expected. 

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information
 airensoft/ovenmediaengine/0.14.2 with host network. 

- Encoder information
We use rtsp-simple-server to manage our feeds, the following setup is our fake testing configuration which generates three test videos.

`./rtsp-simple-server configuration.yaml`

**configuration.yaml**
```
paths:

  fixed:
    runOnInit: ffmpeg -re -f lavfi -i testsrc2=d=3600:s=1280x720:r=24,format=yuv420p -f lavfi -i sine=f=440:b=4 -shortest -c:v libx264 -vf format=yuv420p -preset ultrafast -crf 32 -bf 0 -an -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/fixed -c copy -an -f flv "rtmp://streamingserver.dev:1935/app/cam1"
    runOnReadyRestart: yes

  ptz:
    runOnInit: ffmpeg -re -f lavfi -i testsrc2=d=3600:s=1280x720:r=24,format=yuv420p -f lavfi -i sine=f=440:b=4 -shortest -c:v libx264 -vf format=yuv420p -preset ultrafast -crf 32 -bf 0 -an -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/ptz -c copy -an -f flv "rtmp://streamingserver.dev:1935/app/cam2"
    runOnReadyRestart: yes

  desktop:
    runOnInit: ffmpeg -re -f lavfi -i testsrc2=d=3600:s=1280x720:r=24,format=yuv420p -f lavfi -i sine=f=440:b=4 -shortest -c:v libx264 -vf format=yuv420p -preset ultrafast -crf 32 -bf 0 -an -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/desktop -c copy -an -f flv "rtmp://streamingserver.dev:1935/app/desktop"
    runOnReadyRestart: yes
```

- Player information
No errors

**SETUP INFORMATION AND LOGS**
OME is proxied with Traefik, it's not ideal because HTTP2 internally from traefik to ome isn't used. I also interested in other people's setups for this, Traefik should support proxying the h2 port but haven't had time to change it. 
```
    labels:
      - traefik.enable=true

      - traefik.http.routers.ome.entryPoints=web-secure
      - traefik.http.routers.ome.rule=Host(`ome.ome-test-2.ourdomain.dev`)
      - traefik.http.services.ome.loadbalancer.server.port=8080
      - traefik.http.routers.ome.service=ome

      - traefik.http.routers.ome-webrtc.entrypoints=web-secure
      - traefik.http.routers.ome-webrtc.rule=Host(`webrtc.ome-test-2.ourdomain.dev`)
      - traefik.http.services.ome-webrtc.loadbalancer.server.port=3333
      - traefik.http.routers.ome-webrtc.service=ome-webrtc

```

```
<?xml version="1.0" encoding="UTF-8" ?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	<!-- Host type (origin/edge) -->
	<Type>origin</Type>
	<!-- Specify IP address to bind (* means all IPs) -->
	<IP>*</IP>
	<PrivacyProtection>false</PrivacyProtection>
	<!-- 
	To get the public IP address(mapped address of stun) of the local server. 
	This is useful when OME cannot obtain a public IP from an interface, such as AWS or docker environment. 
	If this is successful, you can use ${PublicIP} in your settings.
	-->
	<StunServer>stun.l.google.com:19302</StunServer>

	<!-- Settings for the ports to bind -->
	<Bind>
		<!-- Enable this configuration if you want to use API Server -->
		
		<Managers>
			<API>
				<Port>${env:OME_API_PORT:8081}</Port>
				<WorkerCount>1</WorkerCount>
			</API>
		</Managers>
		
		<Providers>
			<!-- Push providers -->
			<RTMP>
				<Port>${env:OME_RTMP_PROV_PORT:1935}</Port>
				<WorkerCount>1</WorkerCount>
			</RTMP>
			<SRT>
				<Port>${env:OME_SRT_PROV_PORT:9999}</Port>
				<WorkerCount>1</WorkerCount>
			</SRT>
		</Providers>

		<Publishers>
			<!-- The OVT is protocol for ORIGIN-EDGE -->
			<OVT>
				<Port>${env:OME_ORIGIN_PORT:9000}</Port>
				<WorkerCount>1</WorkerCount>
			</OVT>
                        <LLHLS>
				<Port>8080</Port>
				<WorkerCount>1</WorkerCount>
	  		</LLHLS>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
					<WorkerCount>1</WorkerCount>
					<!-- If you want to use TLS, specify the TLS port -->
					<!-- <TLSPort>3334</TLSPort> -->
				</Signalling>
				<IceCandidates>
					<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
					<IceCandidate>${env:OME_ICE_CANDIDATES:*:10006/udp}</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

<!--
		Enable this configuration if you want to use API Server
		
		<AccessToken> is a token for authentication, and when you invoke the API, you must put "Basic base64encode(<AccessToken>)" in the "Authorization" header of HTTP request.
		For example, if you set <AccessToken> to "ome-access-token", you must set "Basic b21lLWFjY2Vzcy10b2tlbg==" in the "Authorization" header.
	-->
	
	<Managers>
		<Host>
			<Names>
				<Name>*</Name>
			</Names>
	<!--		<TLS>
				<CertPath>path/to/file.crt</CertPath>
				<KeyPath>path/to/file.key</KeyPath>
				<ChainCertPath>path/to/file.crt</ChainCertPath>
			</TLS> -->
		</Host>
		<API>
			<AccessToken>ome-access-token</AccessToken>
	<!--		<CrossDomains>
				<Url>*.airensoft.com</Url>
				<Url>http://*.sub-domain.airensoft.com</Url>
				<Url>http?://airensoft.*</Url>
			</CrossDomains> -->
		</API>
	</Managers>
	

	<VirtualHosts>
		<!--
			You can include multiple XML files by doing the following:
			<VirtualHost include="sites-enabled/*.xml" />
		-->
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			<!--Distribution is a value that can be used when grouping the same vhost distributed across multiple servers. This value is output to the events log, so you can use it to aggregate statistics. -->
			<Distribution>ovenmediaengine.com</Distribution>
			
			<!-- Settings for multi ip/domain and TLS -->
			<Host>
				<Names>
					<!-- Host names
						<Name>stream1.airensoft.com</Name>
						<Name>stream2.airensoft.com</Name>
						<Name>*.sub.airensoft.com</Name>
						<Name>192.168.0.1</Name>
					-->
					<Name>*</Name>
				</Names>
				<!--
				<TLS>
					<CertPath>path/to/file.crt</CertPath>
					<KeyPath>path/to/file.key</KeyPath>
					<ChainCertPath>path/to/file.crt</ChainCertPath>
				</TLS>
				-->
			</Host>

			<!-- Refer https://airensoft.gitbook.io/ovenmediaengine/signedpolicy
			<SignedPolicy>
				<PolicyQueryKeyName>policy</PolicyQueryKeyName>
				<SignatureQueryKeyName>signature</SignatureQueryKeyName>
				<SecretKey>aKq#1kj</SecretKey>

				<Enables>
					<Providers>rtmp,webrtc,srt</Providers>
					<Publishers>webrtc,hls,dash,lldash</Publishers>
				</Enables>
			</SignedPolicy>
			-->

			<!-- Settings for applications -->
			<Applications>
				<Application>
					<Name>app</Name>
					<!-- Application type (live/vod) -->
					<Type>live</Type>

					<OutputProfiles>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
            							<Video>
							               <Bypass>true</Bypass>
						               </Video>
								<!-- <Video>
									<Bypass>false</Bypass>
									<Codec>h264</Codec>
									<Bitrate>3000000</Bitrate>
								</Video> -->
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
							</Encodes>
						</OutputProfile>
					</OutputProfiles>

					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
					</Providers>

					<Publishers>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						<LLHLS>
							<ChunkDuration>0.2</ChunkDuration>
							<SegmentDuration>6</SegmentDuration>
							<SegmentCount>10</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</LLHLS>
						<FILE>
	       					<RootPath>/recordings</RootPath>
							<FilePath>/${VirtualHost}/${Application}/${Stream}/${StartTime:YYYYMMDDhhmmss}_${EndTime:YYYYMMDDhhmmss}.ts</FilePath>
							<InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
						</FILE>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>
```
