### ISSUE TITLE
Recording state "Ready"

### ISSUE THREAD

**Issue by crstian19** [AirenSoft/OvenMediaEngine#816]
Before asking for help, please read the troubleshooting section in the manual carefully.
https://airensoft.gitbook.io/ovenmediaengine/troubleshooting

Please fill out the form below to create an issue. Failure to follow the form may result in late responses or close issues.

**PROBLEM**

Hi, I am testing the API with recording and when I send it to record, the status does not change to recording, it stays in ready.

```

{
  "ptz": {
    "message": "OK",
    "response": [
      {
        "app": "app",
        "createdTime": "2022-07-12T14:19:15.441+00:00",
        "filePath": "/a73bdaf9-d09e-406c-a2aa-2dafdfbc4c0e/2022_07_12-14_19_15/2022_07_12-14_19_15-ptz.mp4",
        "id": "a73bdaf9-d09e-406c-a2aa-2dafdfbc4c0e-ptz",
        "segmentationRule": "discontinuity",
        "state": "ready",
        "stream": {
          "name": "ptz",
          "tracks": []
        },
        "vhost": "default"
      }
    ],
    "statusCode": 200
  },
  "fixed": {
    "message": "OK",
    "response": [
      {
        "app": "app",
        "createdTime": "2022-07-12T14:19:15.444+00:00",
        "filePath": "/a73bdaf9-d09e-406c-a2aa-2dafdfbc4c0e/2022_07_12-14_19_15/2022_07_12-14_19_15-fixed.mp4",
        "id": "a73bdaf9-d09e-406c-a2aa-2dafdfbc4c0e-fixed",
        "segmentationRule": "discontinuity",
        "state": "ready",
        "stream": {
          "name": "fixed",
          "tracks": []
        },
        "vhost": "default"
      }
    ],
    "statusCode": 200
  },
  "desktop": {
    "message": "OK",
    "response": [
      {
        "app": "app",
        "createdTime": "2022-07-12T14:19:15.448+00:00",
        "filePath": "/a73bdaf9-d09e-406c-a2aa-2dafdfbc4c0e/2022_07_12-14_19_15/2022_07_12-14_19_15-desktop.mp4",
        "id": "a73bdaf9-d09e-406c-a2aa-2dafdfbc4c0e-desktop",
        "segmentationRule": "discontinuity",
        "state": "ready",
        "stream": {
          "name": "desktop",
          "tracks": []
        },
        "vhost": "default"
      }
    ],
    "statusCode": 200
  }
}
```

When I try to start recording, the API returns "[HTTP] Duplicate ID already exists (400)".
```

{
  "ptz": {
    "message": "[HTTP] Duplicate ID already exists (400)",
    "statusCode": 400
  },
  "fixed": {
    "message": "[HTTP] Duplicate ID already exists (400)",
    "statusCode": 400
  },
  "desktop": {
    "message": "[HTTP] Duplicate ID already exists (400)",
    "statusCode": 400
  }
}
```

**EXPECTATION**

Recording

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

I'm using Docker image airensoft/ovenmediaengine:0.14.2

- Encoder information

I'm using rtsp-simple-server

```
paths:

  fixed:
    runOnInit: ffmpeg -re -f lavfi -i testsrc2=d=3600:s=1280x720:r=24,format=yuv420p -f lavfi -i sine=f=440:b=4 -shortest -c:v libx264 -vf format=yuv420p -preset ultrafast -crf 32 -bf 0 -an -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/fixed -c copy -an -f flv "rtmp://streamingserver.dev:1935/app/cam1"
    runOnReadyRestart: yes

  ptz:
    runOnInit: ffmpeg -re -f lavfi -i testsrc2=d=3600:s=1280x720:r=24,format=yuv420p -f lavfi -i sine=f=440:b=4 -shortest -c:v libx264 -vf format=yuv420p -preset ultrafast -crf 32 -bf 0 -an -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/ptz -c copy -an -f flv "rtmp://streamingserver.dev:1935/app/cam2"
    runOnReadyRestart: yes

  desktop:
    runOnInit: ffmpeg -re -f lavfi -i testsrc2=d=3600:s=1280x720:r=24,format=yuv420p -f lavfi -i sine=f=440:b=4 -shortest -c:v libx264 -vf format=yuv420p -preset ultrafast -crf 32 -bf 0 -an -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/desktop -c copy -an -f flv "rtmp://streamingserver.dev:1935/app/desktop"
    runOnReadyRestart: yes

```
- Player information

I'm using https://demo.ovenplayer.com

**SETUP INFORMATION AND LOGS**

Please upload Server.xml.
Please upload the entire file /var/log/ovenmediaengine/ovenmediaengine.log. (You may delete your personal information.)
It's hard to find the problem if you post only part of the log. Be sure to upload the entire file.

<?xml version="1.0" encoding="UTF-8"?>

    <Server version="8">
      <Name>OvenMediaEngine</Name>
      
      <Type>origin</Type>

      
      <IP>*</IP>
      <PrivacyProtection>false</PrivacyProtection>

      <StunServer>stun.l.google.com:19302</StunServer>

      <Modules>
        
        <HTTP2>
          <Enable>true</Enable>
        </HTTP2>

        <LLHLS>
          <Enable>true</Enable>
        </LLHLS>

        
        <P2P>
          
          <Enable>false</Enable>
          <MaxClientPeersPerHostPeer>2</MaxClientPeersPerHostPeer>
        </P2P>

      </Modules>

      
      <Bind>
        
        
        <Managers>
          <API>
            <Port>${env:OME_API_PORT:8081}</Port>
            <WorkerCount>1</WorkerCount>
          </API>
	
        </Managers>
        
        <Providers>
          
          <RTMP>
            <Port>${env:OME_RTMP_PROV_PORT:1935}</Port>
            <WorkerCount>1</WorkerCount>
          </RTMP>
          <SRT>
            <Port>${env:OME_SRT_PROV_PORT:9999}</Port>
            <WorkerCount>1</WorkerCount>
          </SRT>
        </Providers>

        <Publishers>
          
          <OVT>
            <Port>${env:OME_ORIGIN_PORT:9000}</Port>
            <WorkerCount>1</WorkerCount>
          </OVT>
          <LLHLS>
            
            <Port>${env:OME_LLHLS_STREAM_PORT:3333}</Port>
            <TLSPort>${env:OME_LLHLS_STREAM_TLS_PORT:3334}</TLSPort>
            <WorkerCount>1</WorkerCount>
          </LLHLS>
          <WebRTC>
            <Signalling>
              <Port>${env:OME_SIGNALLING_PORT:3333}</Port>
              <TLSPort>${env:OME_SIGNALLING_TLS_PORT:3334}</TLSPort>
              <WorkerCount>1</WorkerCount>
            </Signalling>
            <IceCandidates>
              <IceCandidate>*:10000-10005/udp</IceCandidate>
              <TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
              <TcpForce>true</TcpForce>
              <TcpRelayWorkerCount>1</TcpRelayWorkerCount>
            </IceCandidates>
          </WebRTC>
        </Publishers>
      </Bind>

        <Managers>
                <Host>
                        <Names>
                                <Name>*</Name>
                        </Names>
        
                </Host>
                <API>
                        <AccessToken>ome-access-token</AccessToken>
        
                </API>
        </Managers>

      <VirtualHosts>
        
        <VirtualHost include="VHost*.xml" />
        <VirtualHost>
          <Name>default</Name>
          
          <Distribution>ovenmediaengine.com</Distribution>
          
          
          <Host>
            <Names>
              
              <Name>*</Name>
            </Names>
            
          </Host>

          
          <Applications>
            <Application>
              <Name>app</Name>
              
              <Type>live</Type>
              
              <OutputProfiles>
                <OutputProfile>
                  <Name>bypass_stream</Name>
                  <OutputStreamName>${OriginStreamName}</OutputStreamName>

                  

                  <Encodes>
                    <Audio>
                      <Name>bypass_audio</Name>
                      <Bypass>true</Bypass>
                    </Audio>
                    <Video>
                      <Name>bypass_video</Name>
                      <Bypass>true</Bypass>
                    </Video>
                    <Audio>
                      <Codec>opus</Codec>
                      <Bitrate>128000</Bitrate>
                      <Samplerate>48000</Samplerate>
                      <Channel>2</Channel>
                    </Audio>
                    
                  </Encodes>
                </OutputProfile>
              </OutputProfiles>

              <Providers>
                <RTMP />
                <SRT />
              </Providers>

              <Publishers>
                <AppWorkerCount>1</AppWorkerCount>
                <StreamWorkerCount>8</StreamWorkerCount>
                <OVT />
                <WebRTC>
                  <Timeout>30000</Timeout>
                  <Rtx>false</Rtx>
                  <Ulpfec>false</Ulpfec>
                  <JitterBuffer>false</JitterBuffer>
                </WebRTC>
                <LLHLS>
                  <ChunkDuration>0.5</ChunkDuration>
                  <SegmentDuration>6</SegmentDuration>
                  <SegmentCount>10</SegmentCount>
                  <CrossDomains>
                      <Url>*</Url>
                  </CrossDomains>
                </LLHLS>
                <FILE>
                  <RootPath>/recordings</RootPath>
                  <FilePath>/${VirtualHost}/${Application}/${Stream}/${StartTime:YYYYMMDDhhmmss}_${EndTime:YYYYMMDDhhmmss}.ts</FilePath>
                  <InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
                </FILE>
              </Publishers>

            </Application>
          </Applications>
        </VirtualHost>
      </VirtualHosts>
    </Server>

**OTHER HELPFUL INFORMATION**

Please write any information that anyone viewing this issue can reference.
